const fs = require('fs'), path = require('path');
let sharp; try { sharp = require('sharp'); } catch (e) { console.log('sharp niet beschikbaar: originele foto\'s blijven staan'); process.exit(0); }
const dist = path.join(__dirname, 'dist');
const { SITE, MEDIA } = new Function(fs.readFileSync(path.join(dist, 'media.js'), 'utf8') + ';return {SITE, MEDIA};')();
const dec = u => u.split('/').map(decodeURIComponent);
const enc = p => p.map(encodeURIComponent).join('/');
async function one(it) { try { const p = dec(it.src); if (p[0] !== 'media' || p[1] !== 'Foto' || !/\.(jpe?g|png|webp|avif|tiff?)$/i.test(p[p.length - 1])) return; const from = path.join(__dirname, ...p); const name = p[p.length - 1].replace(/\.[^.]+$/, '.jpg'); const rel = p.slice(1, -1); const big = path.join(dist, 'media', ...rel, name), small = path.join(dist, 'thumbs', ...rel, name); fs.mkdirSync(path.dirname(big), { recursive: true }); fs.mkdirSync(path.dirname(small), { recursive: true }); const img = sharp(from, { failOn: 'none' }).rotate(); await img.clone().resize({ width: 2400, height: 2400, fit: 'inside', withoutEnlargement: true }).jpeg({ quality: 82, mozjpeg: true }).toFile(big); await img.clone().resize({ width: 900, height: 900, fit: 'inside', withoutEnlargement: true }).jpeg({ quality: 80, mozjpeg: true }).toFile(small); if (name !== p[p.length - 1]) fs.rmSync(path.join(dist, ...p), { force: true }); it.src = 'media/' + enc([...rel, name]); it.thumb = 'thumbs/' + enc([...rel, name]); } catch (e) { console.log('overgeslagen:', it.src, e.message); } }
async function main() { const list = MEDIA.foto.filter(x => !x.type); let i = 0; await Promise.all(Array.from({ length: 4 }, async () => { while (i < list.length) await one(list[i++]); })); await Promise.all(MEDIA.video.filter(v => v.poster && /^media\/.+\.jpe?g$/i.test(v.poster)).map(async v => { try { const p = dec(v.poster), from = path.join(__dirname, ...p), to = path.join(dist, ...p); const buf = await sharp(from, { failOn: 'none' }).rotate().trim({ background: '#000000', threshold: 12 }).resize({ width: 1400, height: 1400, fit: 'inside', withoutEnlargement: true }).jpeg({ quality: 84, mozjpeg: true }).toBuffer(); fs.mkdirSync(path.dirname(to), { recursive: true }); fs.writeFileSync(to, buf); } catch (e) { console.log('poster overgeslagen:', v.poster, e.message); } })); fs.writeFileSync(path.join(dist, 'media.js'), 'const SITE=' + JSON.stringify(SITE) + ';\nconst MEDIA=' + JSON.stringify(MEDIA) + ';\n'); console.log('Foto\'s geoptimaliseerd: ' + list.filter(x => x.thumb).length + ' van ' + list.length); }
main().catch(e => console.log('optimalisatie mislukt, originelen blijven:', e.message));
